### ISSUE TITLE
Providing a workaround for ignored OpenType features in URLs

### ISSUE THREAD

**Issue by adunning** [lualatex/luaotfload#290] opened 2015-10-31 15:53 UTC
The problem of OpenType features being ignored (#204) appears in many everyday documents through URLs. This is a workaround (from [StackExchange](http://tex.stackexchange.com/questions/264206/cant-get-oldstyle-figures-in-url-with-lualatex)) for fixing this; could it be integrated temporarily until the issue has been properly fixed?

```tex
\makeatletter
  \g@addto@macro\UrlSpecials{%
    \do\0{\mbox{\UrlFont\char`\0}}%
    \do\1{\mbox{\UrlFont\char`\1}}%
    \do\2{\mbox{\UrlFont\char`\2}}%
    \do\3{\mbox{\UrlFont\char`\3}}%
    \do\4{\mbox{\UrlFont\char`\4}}%
    \do\5{\mbox{\UrlFont\char`\5}}%
    \do\6{\mbox{\UrlFont\char`\6}}%
    \do\7{\mbox{\UrlFont\char`\7}}%
    \do\8{\mbox{\UrlFont\char`\8}}%
    \do\9{\mbox{\UrlFont\char`\9}}%
  }
\makeatother
```

**Comment by eroux** [comment] 2015-11-01 10:05
I don't think such a workaround is really reasonable as it might break other things (though I admit I don't fully understand it). I don't think luaotfload will be updated before TeXLive 2016 (due to lack of time of the maintainers), but if you have time you can help up with the maintenance. I'm afraid, though, that the main job for this issue is upstream, you'll have to convince Hans that something must be fixed on the ConTeXt side (Hans doesn't care about LaTeX). I've never run any single ConTeXt compilation in my life, so I'm affraid I cannot help you much...

**Comment by adunning** [comment] 2015-11-01 12:31
That workaround is due to @eg9. I don't fully understand what the problem myself, but it's something that I imagine will affect a large number of people, and it would be good to get some kind of temporary fix in here if at all possible.

**Comment by davidcarlisle** [comment] 2015-11-01 13:04
That patch is probably safe enough, but can't (or at least shouldn't) be in luaotfload, the commands it is modifying are not defined normally. The patch could be offered to url (or hyperref) packages that define \UrlSpecials to use a modified definition in lualatex.

**Comment by eroux** [comment] 2015-11-01 13:42
@davidcarlisle good idea!

**Comment by phi-gamma** [comment] 2015-11-21 16:55
I agree with @davidcarlisle.

From my understanding this is an issue with how those URL macros are
defined.

**Closed by phi-gamma** 2015-11-21 16:55 UTC
Labels: invalid

**Comment by adunning** [comment] 2015-11-21 16:58
Neither the `url` or `hyperref` package have been updated in some time; does anyone know how to get in touch with the maintainers?

**Comment by davidcarlisle** [comment] 2015-11-21 17:12
Heiko's email is in the subtitle of most of his packages eg `texdoc ifpdf` But he's lagging a bit behind and the upcoming luatex 0.85 breaks several of them, so several will need at least minor updates.

**Comment by jfbu** [comment] 2016-04-30 07:16
@phi-gamma, @adunning 

The only relevant aspect of the `\url` macros is that they use math mode. As pointed out by @adunning this issue can affect many people, and not only those using `\url` macro.

https://github.com/lualatex/luaotfload/issues/204#issuecomment-215943258

**Comment by jfbu** [comment] 2016-04-30 07:20
@eroux 

the problem is not on the context side

https://github.com/lualatex/luaotfload/issues/204#issuecomment-215943258

**Comment by jfbu** [comment] 2016-05-03 07:24
I have posted a (seemingly partial) patch to this problem at http://tex.stackexchange.com/questions/264206/cant-get-oldstyle-figures-in-url-with-lualatex/307585#307585

@davidcarlisle there is perhaps a need for LaTeX to revise what `\DeclareSymbolFont` does to take into account the `LuaTeX+luaotfload+unknown things "upstream"` situation.

**Comment by jfbu** [comment] 2016-05-03 07:43
The fix is only partial because it does not seem to work with multiple features, but it does one at a time, thus `onum` works, `tnum` and `pnum` work, but `onum` together with `tnum` only activates Old Style, in this case of TeX Gyre Termes.
