### ISSUE TITLE
Can't load font with too many OT features requested

### ISSUE THREAD

**Issue by wspr** [lualatex/luaotfload#424] opened 2018-08-13 10:23 UTC
A bit of a strange one:

```
\ifdefined\XeTeXversion\else\input luaotfload.sty\fi

\font\x="[iosevka-type-slab-regular.ttf]:mode=node;script=latn;language=DFLT;+tlig
;+cv01=0;+cv02=0;+cv03=0;+cv04=0;+cv05=0;+cv06=0;+cv07=0;+cv08=0;+cv09=0;+cv10=
0;+cv11=0;+cv12=0;+cv13=0;+cv14=0;+cv15=0;+cv16=0;+cv17=0;+cv18=0;+cv19=0;+cv20
=0;+cv21=0;color=AA0000FF;"\x

ailßtQ\#3y1f

\bye
```

Works fine in XeTeX; with luaotfload produces:

```
! Font \x=[iosevka-type-slab-regular.ttf]:mode=node;script=latn;language=DFLT;+
tlig ;+cv01=0;+cv02=0;+cv03=0;+cv04=0;+cv05=0;+cv06=0;+cv07=0;+cv08=0;+cv09=0;+
cv10= 0;+cv11=0;+cv12=0;+cv13=0;+cv14=0;+cv15=0;+cv16=0;+cv17=0;+cv18=0;+cv19=0
;+cv20 =0;+cv21=0;c.
<to be read again> 
\x 
l.7 =0;+cv21=0;color=AA0000FF;"\x
                               
? h
I wasn't able to read the size data for this font,
so I will ignore the font specification.
[Wizards can fix TFM files using TFtoPL/PLtoTF.]
```

The font is available here: <https://github.com/be5invis/Iosevka/releases>

**Comment by eg9** [comment] 2018-08-13 11:10
If I write the font specification on a single line, I get

```tex
! Font \x=[iosevka-type-slab-regular.ttf]:mode=node;script=latn;language=DFLT;+
tlig;+cv01=0;+cv02=0;+cv03=0;+cv04=0;+cv05=0;+cv06=0;+cv07=0;+cv08=0;+cv09=0;+c
v10=0;+cv11=0;+cv12=0;+cv13=0;+cv14=0;+cv15=0;+cv16=0;+cv17=0;+cv18=0;+cv19=0;+
cv20=0;+cv21=0;colo.
```
and the string is 247 character long. Upon removing, say, ```language=DFLT;```, the font specification is accepted.

This seems to hit a limit on the length of a string, in Lua or in ```luaotfload```.

**Comment by wspr** [comment] 2018-08-13 11:25
@eg9 — I agree it seems string length related, and Lua almost certainly isn't limited by a finite string length here...

**Comment by u-fischer** [comment] 2018-08-18 11:19
With a newer fontloader the loading of the fonts fail completly, both in latex and context,.

~~~~
\starttext

\font\x={file:iosevka-type-slab-regular.ttf}
\x

ablub
\stoptext
~~~~

gives 

~~~~
..ext/tex/texmf-context/tex/context/base/mkiv/font-oup.lua:2137: bad argument #1 to 'for iterator' (table expected, got nil)
~~~~

I sent a bug report to the context list.

**Comment by u-fischer** [comment] 2018-09-25 10:18
The length of the font name seems to be restricted to 255 by the engine. See https://github.com/u-fischer/lua-font-pond/issues/14#issuecomment-424271806.  So the whole list of features can not be used. The best that the fontloader can do here, is to cut away only at safe places.

**Comment by eg9** [comment] 2018-09-25 10:20
@u-fischer Is that a Lua limitation or just imposed by LuaTeX? In the latter case maybe the LuaTeX team can fix.

**Comment by u-fischer** [comment] 2018-09-25 10:22
@eg9  The code suggests that it is done to be compatible with the dvi format:
https://github.com/TeX-Live/luatex/blob/8113cb51f4899c4e81a363c1e10d63c673b100ac/source/texk/web2c/luatexdir/font/dofont.c#L84

**Comment by wspr** [comment] 2018-09-25 14:44
Sigh :) Can I cross my fingers this ISN’T a problem in regular pdfluatex and skipping the check in that case will “just work”?

**Comment by u-fischer** [comment] 2018-09-27 13:00
@wspr sorry I don't think that I understand your question ;-(. 

Imho the option are 

* remove (either fontspec or the fontloader) features from the list if it gets too long (and warn the user)
* get Hans/Luigi to change the engine so that it accepts longer names (always or only in pdf-mode)
* find a way to create a new open type feature "cvXX" on-the-fly with combines the list above and allows to use +cvXX instead of the list (no idea if this is possible).

**Comment by u-fischer** [comment] 2018-10-04 21:40
@wspr  well it looks as if one can attach a list of features to the script, and it looks as if the list can be quite long (not so easy to test if everything is working as the character variants are in parts for the same char).

~~~~
\documentclass{article}
\usepackage{luacode}
\begin{luacode}
    
test = {
  ["cv01"]=true,["cv02"]=true,["cv03"]=true,["cv04"]=true,["cv05"]=true,
  ["cv06"]=true,["cv07"]=true,["cv08"]=true,["cv09"]=true,["cv10"]=true,
  ["cv11"]=true,["cv12"]=true,["cv13"]=true,["cv14"]=true,["cv15"]=true,
  ["cv16"]=true,["cv17"]=true,["cv18"]=true,["cv19"]=true,["cv20"]=true,
  ["cv21"]=true,["cv22"]=true,["cv23"]=true,["cv24"]=true,["cv25"]=true,
  ["cv26"]=true,["cv27"]=true,["cv28"]=true,["cv29"]=true,  
  ["ss01"]=true,
  ["color"]="AA0000FF",["tlig"]=true,
 }



\end{luacode}
\begin{document}

\directlua{luaotfload.features.defaults.latn=test}

\font\x={file:iosevka-type-slab-regular.ttf:mode=node;script=latn;}
\x abc -- xxx

ffig 01234 Abc

\directlua{luaotfload.features.defaults.latn={}}
\font\y={file:iosevka-type-slab-regular.ttf:mode=node;script=latn;}
\y abc -- xxx

ffig 01234 Abc

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/46504594-9cd42600-c82e-11e8-8d29-d0f323dcd937.png)

**Comment by zauguin** [comment] 2018-10-10 12:50
If there is no need for querying the fontname, adding
the line

    \directlua{luaotfload.aux.stop_rewrite_fontname()}
before loading the font fixes this. Then the features are not part of the fontname, so the 255 character limit only applies to the actual name `iosevka-type-slab-regular`.

``` TeX
\input luaotfload.sty
\directlua{luaotfload.aux.stop_rewrite_fontname()}

\font\x="[iosevka-type-slab-regular.ttf]:mode=node;script=latn;language=DFLT%
;+cv01=0;+cv02=0;+cv03=0;+cv04=0;+cv05=0;+cv06=0;+cv07=0;+cv08=0;+cv09=0;+cv10=%
0;+cv11=0;+cv12=0;+cv13=0;+cv14=0;+cv15=0;+cv16=0;+cv17=0;+cv18=0;+cv19=0;+cv20%
=0;+cv21=0;color=AA0000FF;-tlig;"
\font\y="[iosevka-type-slab-regular.ttf]:mode=node;script=latn;language=DFLT%
;+cv01=0;+cv02=0;+cv03=0;+cv04=0;+cv05=0;+cv06=0;+cv07=0;+cv08=0;+cv09=0;+cv10=%
0;+cv11=0;+cv12=0;+cv13=0;+cv14=0;+cv15=0;+cv16=0;+cv17=0;+cv18=0;+cv19=0;+cv20%
=0;+cv21=0;color=AA0000FF;+tlig;"

\x abc -- xxx

\y abc -- xxx

\bye
```
![longfont](https://user-images.githubusercontent.com/962229/46737351-906f2380-cc9b-11e8-9d2d-8d7ed5632da7.png)

**Comment by u-fischer** [comment] 2018-10-10 15:25
@zauguin  interesting ;-). Imho fontspec uses \fontname and expects it to hold the feature list. But one could probably sometime in the feature offer other means to store and retrieve it.

**Comment by khaledhosny** [comment] 2018-11-12 18:39
What about creating a global table (or attached to any of the other global tables) of parsed font specifications, and if the font name is longer than the LuaTeX limit, replace the name with base file name (so that it can also handle overlong file paths) and a special key pointing to the specification index in that table i.e.:
```
\font\x="[iosevka-type-slab-regular.ttf]:xxx-otflspec=1
```
And read the spec from there when seeing such a font. (the `xxx` should hopefully signal that this is a private option, and users shouldn’t set it).

This way macro code can continue doing what they do now and the limitation is worked around.

**Comment by zauguin** [comment] 2018-11-12 19:59
@khaledhosny I recently looked into something similar: Just replacing overlong names with `id:<insert_fontid_here>`. Some font name can be appended to make this user-readable. There is no need for a custom table because LuaTeX also keeps a indexed list of these fonts. (And additionally the fontloader keeps a second one...)
This also would make loading them more efficient.

The problem is that it does not fix the entire problem: There are three uses of `\fontname` I am aware of which fail for replaced fontnames:

1. `fontspec` queries `fontname` to get a list of active features. This will always break if we shorten the fontname because of many features.
2. The TU encoding in the LaTeX core splits the `fontname` and reassembles it to change the `tlig` value.
This does not work anymore if a pseudo-fontname is used.
3. `fontspec` and the NFSS use `\fontname` to alias a font without changing the fontname. This would be fixed by providing different but still parsable fontnames.

So really fixing this needs changes in fontspec (for 1.) and in LaTeX (for 2.).
While we are at it we probably should change the code affected by 3: Using fontname for this is inefficient and at least in fontspec a comment suggests that it leads to problems because of missing fontdimens.

Of course, after fixing this stuff we probably still want to replace the fontname with something parsable in case other macros rely on this.

**Comment by khaledhosny** [comment] 2018-11-12 20:11
Thanks, things are clearer now. May be it is worth checking if the engine can be fixed instead, and if this is really a DVI limitation then may be abort with a better error only when in DVI mode.

**Comment by khaledhosny** [comment] 2018-11-12 20:18
I just tried commenting out the code linked in https://github.com/lualatex/luaotfload/issues/424#issuecomment-424287750, loading the font now works in pdf mode, and in dvi mode the font name is indeed truncated (from the beginning!).

**Comment by zauguin** [comment] 2018-11-12 20:23
@khaledhosny Some time ago I tried changing it and got SegFaults, but things might have changed since then. Are you going to propose the patch for LuaTeX?

**Comment by khaledhosny** [comment] 2018-11-12 20:26
Checking for `get_o_mode() == OMODE_DVI` as well retains the current behavior in dvi mode and fixes pdf mode. I think I’m going to propose this patch:
```diff
diff --git a/source/texk/web2c/luatexdir/font/dofont.c b/source/texk/web2c/luatexdir/font/dofont.c
index b23368d83..a401a8b1b 100644
--- a/source/texk/web2c/luatexdir/font/dofont.c
+++ b/source/texk/web2c/luatexdir/font/dofont.c
@@ -81,7 +81,7 @@ static int do_define_font(int f, const char *cnom, scaled s, int natural_dir)
             set_skew_char(f, default_skew_char_par);
         }
     }
-    if (font_name(f) && strlen(font_name(f)) > 255) {
+    if (get_o_mode() == OMODE_DVI && font_name(f) && strlen(font_name(f)) > 255) {
         /*tex
 
             The font name has to fit in the dvi file's single byte storage. There
```

**Comment by wspr** [comment] 2018-11-13 12:23
Thanks for the investigations. I like Khaled's approach. Please note I'm very happy to update fontspec internals in cases like this, although I'm sometimes slow to reply...

**Comment by khaledhosny** [comment] 2018-11-13 16:23
https://mailman.ntg.nl/pipermail/dev-luatex/2018-November/006134.html

**Comment by khaledhosny** [comment] 2018-11-13 23:20
Patch was merged, binaries from https://github.com/khaledhosny/luahbtex/releases/tag/2018-11-13-0cac42c should have it (they work like regular `luatex` despite the name).

**Comment by u-fischer** [comment] 2019-08-14 16:59
the original document compiles fine for me in a current texlive 2019 so I'm closing this as resolved.

**Closed as completed by u-fischer** 2019-08-14 16:59 UTC
