### ISSUE TITLE
Unable to index field 'spacing' when generating characters from lua code

### ISSUE THREAD

**Issue by henryso** [lualatex/luaotfload#372] opened 2016-07-22 21:54 UTC
Related to gregorio-project/gregorio#1188, when we generate a glyph table from Lua code under TeX Live 2016, we get an error:

```
(/usr/local/texlive/2016/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua))) (/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-06-16.lua:15598: attempt to index field 'spacing' (a nil value)
```

Running under TeX Live 2015, this error does not occur.  If I directly enter what the Lua code would generate, this error also does not appear to occur (under TeX Live 2016).

The MWE for this is at https://gist.github.com/henryso/d94e28ee96bf1e5d3b9f8832b723ccf3

Edit: Under TeX Live 2015, this MWE needs the greextra.ttf font is available under TeX Live 2016.

**Comment by phi-gamma** [comment] 2016-07-28 21:00
···<date: 2016-07-22, Friday>···<from: Henry So>···

> Related to gregorio-project/gregorio#1188, when we generate a glyph table from Lua code under TeX Live 2016, we get an error:
> ```
> (/usr/local/texlive/2016/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua))) (/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-06-16.lua:15598: attempt to index field 'spacing' (a nil value)

Thanks for the report! I can reproduce it with the latest release
but not with the latest master.

Philipp

**Comment by rpspringuel** [comment] 2016-09-17 20:59
Are there any plans to make another release of luaotfload onto CTAN that will include this fix?

**Comment by phi-gamma** [comment] 2016-09-20 05:56
···<date: 2016-09-17, Saturday>···<from: Br. Samuel Springuel>···

> Are there any plans to make another release of luaotfload onto
> CTAN that will include this fix?

Plans? Sure =) Lots of plans!

The next release will probably become 2.8 because of massive
changes in the fontloader. Unfortunately, there’s a bug in the
new code that causes a crash with node mode. Originally I wanted
to push out a new release before the Kalenberg meeting but since
Hans is probably busy right now doing other things, this issue is
blocking the release for the time being. Sorry.

Best,
Philipp

**Comment by phi-gamma** [comment] 2016-09-20 06:22
···<date: 2016-09-17, Saturday>···<from: Br. Samuel Springuel>···

> Are there any plans to make another release of luaotfload onto CTAN that will include this fix?

I’ve put up a release candidate:

    https://github.com/lualatex/luaotfload/releases/tag/v2.8-rc1

If you wish, you can test the latest code with it. My tests are
promising, but it’s not going to be published until there’s an
upstream fix for that crash I mentioned.

Philipp

**Comment by kiryph** [comment] 2017-01-26 15:23
I have encountered probably a related error:

`[5]error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-06-16.lua:11449: attempt to perform arithmetic on local 'factor' (a nil value)`

Are there any chances there will be release any time soon?

**Comment by phi-gamma** [comment] 2017-01-29 20:43
New release v2.8, please retest. Thanks!

**Comment by rpspringuel** [comment] 2017-02-21 13:42
New release works great for me.

**Comment by u-fischer** [comment] 2018-10-05 21:27
Closing as it looks as if the problem has been resolved in previous versions.

**Closed by u-fischer** 2018-10-05 21:27 UTC
Labels: font loader bug
