### ISSUE TITLE
Invalid character leads to fatal error

### ISSUE THREAD

**Issue by jpintar** [lualatex/luaotfload#264] opened 2015-02-04 05:01 UTC
The following example

    \input luaotfload.sty
    \font\amor=file:AmorSerifTextPro.otf\amor
    Sphinx of black quartz, judge my vow. 1234567890
    \bye

fails to compile with LuaTeX, with the following error logged

    luaotfload | db : Font names database loaded from C:/texlive/2014/texmf-var/luat
    ex-cache/generic/names/luaotfload-names.luc(load luc: C:/texlive/2014/texmf-var/
    luatex-cache/generic/fonts/otf/amorseriftextpro.luc) [1{c:/Users/USER/.texlive20
    14/texmf-var/fonts/map/pdftex/updmap/pdftex.map}])<./AmorSerifTextPro.otf
    !LuaTeX error (file ./AmorSerifTextPro.otf): Invalid character.
     ==> Fatal error occurred, no output PDF file produced!

However, since the following compiles in XeTeX without any issues

    \font\amor="[AmorSerifTextPro.otf]"\amor
    Sphinx of black quartz, judge my vow. 1234567890
    \bye

I suspect the problem may have to do with luaotfload, rather the font itself (the problematic font is from the [Storm Type Foundry](http://www.stormtype.com/family-amor-serif-pro.html)).

**Comment by phi-gamma** [comment] 2015-02-05 05:16
···<date: 2015-02-03, Tuesday>···<from: jpintar>···

> The following example
> 
>     \input luaotfload.sty
>     \font\amor=file:AmorSerifTextPro.otf\amor
>     Sphinx of black quartz, judge my vow. 1234567890
>     \bye

What constellation of program versions are we talking about? (You
should be able to get the necessary information by running
``luaotfload-tool --version``).

> fails to compile with LuaTeX, with the following error logged
> 
>     luaotfload | db : Font names database loaded from C:/texlive/2014/texmf-var/luat
>     ex-cache/generic/names/luaotfload-names.luc(load luc: C:/texlive/2014/texmf-var/
>     luatex-cache/generic/fonts/otf/amorseriftextpro.luc) [1{c:/Users/USER/.texlive20
>     14/texmf-var/fonts/map/pdftex/updmap/pdftex.map}])<./AmorSerifTextPro.otf
>     !LuaTeX error (file ./AmorSerifTextPro.otf): Invalid character.
>      ==> Fatal error occurred, no output PDF file produced!

Judging from the error message, this looks like a problem on the
Luatex side. I’ll have a closer look at it soon.

> I suspect the problem may have to do with luaotfload, rather
> the font itself (the problematic font is from the [Storm Type
> Foundry](http://www.stormtype.com/family-amor-serif-pro.html)).

Looks like proprietary font :/ This is going to be difficult to
verify. If it really happens exclusively with this font it would
help if you could

  * check what happens if you open the file in Fontforge; and

  * run the file through ttx and see whether it complains about
    anything.

Best regards
Philipp

**Comment by jpintar** [comment] 2015-02-05 06:19
Sorry, I should obviously have included that! LuaTeX v. 0.79.1, luaotfload v. 2.5-4.

I'll do more poking about the font first thing tomorrow, but for now:
* file opens in Fontforge without any complaints
* if I convert the font to TTF using Fontforge, the compilation goes through without errors in both XeTeX and LuaTeX

Thanks for looking into this!
Jura

**Comment by jpintar** [comment] 2015-02-05 17:18
I can now also confirm that the font can be dumped to a TTX file without complaint. If you have any suggestions for what specific problems with the font I should look for, just let me know.

Btw, the error does not occur with any other font in the same family.

**Comment by phi-gamma** [comment] 2015-02-14 19:49
···<date: 2015-02-03, Tuesday>···<from: jpintar>···

>     luaotfload | db : Font names database loaded from C:/texlive/2014/texmf-var/luat
>     ex-cache/generic/names/luaotfload-names.luc(load luc: C:/texlive/2014/texmf-var/
>     luatex-cache/generic/fonts/otf/amorseriftextpro.luc) [1{c:/Users/USER/.texlive20
>     14/texmf-var/fonts/map/pdftex/updmap/pdftex.map}])<./AmorSerifTextPro.otf
>     !LuaTeX error (file ./AmorSerifTextPro.otf): Invalid character.
>      ==> Fatal error occurred, no output PDF file produced!
> 
> However, since the following compiles in XeTeX without any issues

I’ve looked at the issue and it would appear that the error
message comes from inside Luatex itself (writecff.w). That means
we’re not really in a favorable position to debug troubles with a
proprietary font.

You could try loading the file directly, without the fontloader
involved. Just run this script through ``texlua`` in the same
directory as the font file:

    #!/usr/bin/env texlua
    local fnt = fontloader.open "./AmorSerifTextPro.otf"
    local tbl = fontloader.to_table (fnt)
    fontloader.close(fnt)

If that fails then the issue is on the Luatex side. In addition,
you could try loading the font from Context:

    \starttext
      \definedfont[file:AmorSerifTextPro.otf at 12pt]
      Sphinx of black quartz, judge my vow. 1234567890
    \stoptext

Should that fail, then the issue is definitely on the Luatex or
fontloader side. You could then continue upstream and notify Hans
and Luigi about the matter. In any case, let me know about your
findings.

Best
Philipp

**Comment by jpintar** [comment] 2015-02-14 23:43
I ran the script with texlua and got no error messages, but ConTeXt would not compile the example and I got the same error message as before. I'll write to the ConTeXt mailing list next.

Thanks again for looking into this!
Jura

**Comment by phi-gamma** [comment] 2015-02-15 07:10
···<date: 2015-02-14, Saturday>···<from: jpintar>···

> I ran the script with texlua and got no error messages, but
> ConTeXt would not compile the example and I got the same error
> message as before. I'll write to the ConTeXt mailing list next.

Aha, so it is as I thought: The error does not happen during
loading, but when writing to the PDF. That might still indicate
that the issue can / should be fixed on the fontloader side.

It’s weird though that it’s triggered by that one font face only.

**Comment by phi-gamma** [comment] 2015-11-21 19:44
> ConTeXt would not compile the example and I got the same error message as before

@jpintar Any updates on this?

**Comment by phi-gamma** [comment] 2015-12-09 22:54
Closing; please reopen if appropriate.

**Closed by phi-gamma** 2015-12-09 22:54 UTC
Labels: font loader bug
