### ISSUE TITLE
Problem with libertine_R.otf: it can't be loaded

### ISSUE THREAD

**Issue by u-fischer** [lualatex/luaotfload#269] opened 2015-04-30 16:52 UTC
I have a problem with this document:

~~~~~~
\documentclass{article}
\usepackage{fontspec}

% works
%\setmainfont{LinLibertine_R}[Extension=.otf]
%\setmainfont{texgyrepagella-regular.otf}
% setmainfont{LinLibertine_RI.otf}

%fails
\setmainfont{LinLibertine_R.otf}

\begin{document}
blb
\end{document} 
~~~~~~

This fails for me (Texlive 2015, 2014, miktex) with the error message

~~~~~
! LuaTeX error ...ad-texmf/tex/luatex/luaotfload/fontloader-fontloader.lua:5869:
 font loading failed.
<to be read again> 
\scan_stop: 
l.11 \setmainfont{LinLibertine_R.otf}
~~~~~

The curious thing is that for this font a luc and a lua is created in fonts/**afm** and luaotfload is reading this file:

~~~~~
luaotfload | load : path lookup of "LinLibertine_R" unsuccessful, falling back t
o file:(compiling luc: D:/texlive/2015/texmf-var/luatex-cache/generic/fonts/afm/
LinLibertine_R.luc)
~~~~~

The content of the lua is

~~~~~
return {
 ["cache_version"]=1.41,
 ["descriptions"]={},
 ["goodies"]={},
 ["metadata"]={
  ["filename"]="LinLibertine_R",
 },
 ["pfbsize"]=0,
 ["pfbtime"]=0,
 ["properties"]={
  ["hasitalics"]=false,
 },
 ["resources"]={
  ["creator"]="context mkiv",
  ["filename"]="d:/texlive/2015/texmf-dist/tex/latex/libertine/LinLibertine_R.tex",
  ["marks"]={},
  ["names"]={},
  ["originals"]={},
  ["private"]=983040,
  ["tounicode"]={},
  ["unicodes"]={
   ["hyphen"]=45,
   ["space"]=32,
   ["zwj"]=8205,
   ["zwnj"]=8204,
  },
  ["version"]=1.41,
 },
 ["size"]=189991,
 ["time"]=1428919682,
}
~~~~~

So it looks as if for some reason luaotfload thinks the font is a postscript font -- but only if it loaded as `\setmainfont{LinLibertine_R.otf}`. 

I tried to test also with the master branch at  https://github.com/phi-gamma/luaotfload/tree/master (with the same error) but I'm not sure if I installed everything correctly as the makefile failed on windows and I had to remove some parts.

**Comment by phi-gamma** [comment] 2015-04-30 20:44
Thanks for the report!

···<date: 2015-04-30, Thursday>···<from: u-fischer>···

> I have a problem with this document:
> 
> ~~~~~~
> \documentclass{article}
> \usepackage{fontspec}
> 
> % works
> %\setmainfont{LinLibertine_R}[Extension=.otf]
> %\setmainfont{texgyrepagella-regular.otf}
> % setmainfont{LinLibertine_RI.otf}
> 
> %fails
> \setmainfont{LinLibertine_R.otf}
> 
> \begin{document}
> blb
> \end{document} 
> ~~~~~~
> 
> This fails for me (Texlive 2015, 2014, miktex) with the error message

Weird, it builds here just fine (pretest, Linux). There is at
least one known issue:

    https://github.com/lualatex/luaotfload/issues/263

where there is some interference with the loading chain when
other formats are present. Could there be an “AFM” companion to
the font lying around some place?

> ~~~~~
> ! LuaTeX error ...ad-texmf/tex/luatex/luaotfload/fontloader-fontloader.lua:5869:
>  font loading failed.
> <to be read again> 
> \scan_stop: 
> l.11 \setmainfont{LinLibertine_R.otf}
> ~~~~~

What happens if you move fontspec out of the way, e. g.

    \input luaotfload.sty
    \font \mainfont = file:LinLibertine_R.otf at 42pt
    {\mainfont blb}
    \bye

with Plain TeX? Still a lookup failure? Then please try
rebuilding the font database omitting the AFM format explicitly:

    luaotfload-tool -uf --formats=otf,ttf,ttc,dfont

(which is the default, btw.). Does it still occur?

> The content of the lua is
> 
> ~~~~~
> return {
> ...
>  ["resources"]={
>   ["creator"]="context mkiv",
>   ["filename"]="d:/texlive/2015/texmf-dist/tex/latex/libertine/LinLibertine_R.tex",

Does this file exist? There might arise some interference due to
a file name being interpreted as a .tex file on the kpse end. If
it exists, try moving it out of the way and see what happens.
What does

    kpsewhich LinLibertine_R.otf

point to?

> So it looks as if for some reason luaotfload thinks the font is
> a postscript font -- but only if it loaded as
> `\setmainfont{LinLibertine_R.otf}`. 

Might be related to the font lookup being explicit as a file
which is dispatched via an entirely different path than name
lookups.

> I tried to test also with the master branch at
> https://github.com/phi-gamma/luaotfload/tree/master (with the
> same error) but I'm not sure if I installed everything correctly
> as the makefile failed on windows and I had to remove some parts. 

With the latest version you could also try these configuration
variables (local ``luaotfload.conf`` should be fine):

    [run]
        log-level = 6
        definer   = info_patch

This will output some extra debugging messages, especially
concerning the font lookup and loading status.

**Comment by u-fischer** [comment] 2015-04-30 22:02
> >        ["filename"]="d:/texlive/2015/texmf-dist/tex/latex/libertine/LinLibertine_R.tex",
> Does this file exist? There might arise some interference due to
> a file name being interpreted as a .tex file on the kpse end. If
> it exists, try moving it out of the way and see what happens

You hit the nail. The file exists (also for three other fonts which have the same problem), it contains some glyph definitions for the sty, and removing it solves the problem. What would be the best permanent solution? Should libertine rename the files? And why isn't linux affected? Perhaps because file names are case sensitive?

**Comment by phi-gamma** [comment] 2015-05-01 05:33
···<date: 2015-04-30, Thursday>···<from: u-fischer>···

>  > >        ["filename"]="d:/texlive/2015/texmf-dist/tex/latex/libertine/LinLibertine_R.tex",
> > Does this file exist? There might arise some interference due to
> > a file name being interpreted as a .tex file on the kpse end. If
> > it exists, try moving it out of the way and see what happens
> 
> You hit the nail. The file exists (also for three other fonts
> which have the same problem), it contains some glyph definitions
> for the sty, and removing it solves the problem. What would be
> the best permanent solution? Should libertine rename the files?
> And why isn't linux affected? Perhaps because file names are case
> sensitive?

This might be due to a loading order. It’s possible that in case
of contention over the suffix-less filename, kpse returns
whatever it finds first. Usually this isn’t a problem because we
do lookups by format (``.otf``) first and only use the generic
lookup as fallback. Normally this ensures that font files are
found if present. I’m really curious as to the Plaintex example I
gave. If that does work for you, then we’re going to have to
examine what exactly Fontspec does -- does it remove the
extension?

**Comment by u-fischer** [comment] 2015-05-01 09:51
Sorry I was yesterday evening on my tablet and it is more difficult to write long texts there. So here more info

1. Yes without fontspec it works.
2. `kpsewhich LinLibertine_R` returns the LinLibertine_R.tex (as only hit) (but this works only for `.tex`, `kpsewhich article` returns nothing, so it works similar to `\input`). 
3. fontspec does remove font extensions (in `\__fontspec_sanitise_fontname:Nn`). 
4. If I remove `.otf` from this list by using `\DeclareFontsExtensions{.ttf,.OTF,.TTF,.ttc,.TTC,.dfont}` after fontspec then the font works fine.

**Comment by phi-gamma** [comment] 2015-11-21 21:25
Tagging this as a “invalid” because the issue is caused by some unwanted
interaction between Fontspec and Kpathsea. @u-fischer did you follow up
on this someplace else?

**Comment by phi-gamma** [comment] 2015-12-09 22:54
Closing this.

**Closed by phi-gamma** 2015-12-09 22:54 UTC
Labels: invalid
