### ISSUE TITLE
Problems with luaotfload and the dad font

### ISSUE THREAD

**Issue by yannis1962** [lualatex/luaotfload#415] opened 2017-06-06 22:11 UTC
dear Philipp,

two years ago I asked for help concerning compatibility of lua font loading,
now I attempted to include the changes you suggested into my package,
but it doesn't work.

Here is what happens:

1) when I don't use luaotfload everything works fine

2) when I load fontspec at some time, whether before or after dad,
both OFM and TTF fonts are found and loaded, but the smart ligatures of
my OFM font are not executed and all glyphs are in isolated form.

Interestingly enough, this happens only with one font among three
(I supply plain, bold and monospace, the problem occurs only for plain).

Do you think you have some time to investigate what is happening?

Here are the versions of packages I'm using:

Package: fontspec 2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTeX
 (/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload.sty
Package: luaotfload 2016/06/16 v2.7 OpenType layout system
Lua module: luaotfload-main 2016/06/16 2.70003 OpenType layout system.
Lua module: lualibs 2016-04-06 2.4 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2016-04-06 2.4 ConTeXt Lua libraries -- extended collection.(using write cache: /usr/local/texlive/2016/texmf-var/luatex-cache/generic)(using read cache: /usr/local/texlive/2016/texmf-var/luatex-cache/generic /Users/yannis/.texlive2016/texmf-var/luatex-cache/generic)
luaotfload | conf : Root cache directory is /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names.
luaotfload | init : Loading fontloader “fontloader-2016-06-16.lua” from kpse-resolved path “/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/fontloader-2016-06-16.lua”.
Lua-only attribute luaotfload@state = 1
Lua-only attribute luaotfload@noligature = 2
Lua-only attribute luaotfload@syllabe = 3
luaotfload | init : Context OpenType loader version “3.023”
Inserting `luaotfload.node_processor' at position 1 in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' at position 1 in `hpack_filter'.
Inserting `luaotfload.define_font' at position 1 in `define_font'.
Lua-only attribute luaotfload_color_attribute = 4
luaotfload | conf : Root cache directory is /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names.
Inserting `luaotfload.aux.set_sscale_dimens' at position 1 in `luaotfload.patch_font'.
Inserting `luaotfload.aux.patch_cambria_domh' at position 2 in `luaotfload.patch_font'.
Inserting `luaotfload.aux.fixup_fontdata' at position 1 in `luaotfload.patch_font_unsafe'.
Inserting `luaotfload.aux.set_capheight' at position 3 in `luaotfload.patch_font'.
Inserting `luaotfload.rewrite_fontname' at position 4 in `luaotfload.patch_font'.
luaotfload | main : initialization completed in 0.144 seconds

Thanks in advance,

Yannis

**Comment by yannis1962** [comment] 2017-08-08 16:42
No news on that issue??

**Comment by u-fischer** [comment] 2018-10-05 11:07
Check if it works with the new luaotfload 2.91. If not please add an issue to https://github.com/u-fischer/luaotfload/issues. Needed is a compilable complete example and the fonts.

**Comment by u-fischer** [comment] 2018-10-09 08:16
I compared an example from the older issue #273 

~~~~
\documentclass{article}
\usepackage{dad}
%\usepackage{fontspec}
\begin{document}
\Huge\arab{AlkitAbu AlkabYru}
\Huge\arab{الكتابُ الكبيرُ}
\end{document}

~~~~

I tested with and without fontspec, and with and without luaotfload (on texlive 2018 by suppressing the loading in the format, and by running it in texlive 2014). 

In all cases the output was identical

![image](https://user-images.githubusercontent.com/4047173/46655520-19a72d00-cbac-11e8-8f39-6d405336b658.png)

So I'm assuming that the problem is resolved and I close the issue.

Side remark: the package should if possible be updated so that it no longer requires the luatex85 package.

**Closed as completed by u-fischer** 2018-10-09 08:16 UTC
