### ISSUE TITLE
luaotfload writes database to TEXMFSYSVAR if the latter is writable. Shouldn't it use TEXMFVAR ?

### ISSUE THREAD

**Issue by jfbu** [lualatex/luaotfload#360] opened 2016-05-16 09:34 UTC
I have determined that luatex-cache is created in TEXMFSYSVAR if the user
account has write access to it. This seems unexpected because if two
users XXX and YYY both have write access then they could overwrite each other
database (fonts may differ, as they may reside in personal folders).

Actually the umask of YYY for example is used in creating first the luatex-cache
and then XXX has typically (say if YYY's umask is 22 as usual)
no write access anymore to it. Testing shows that
luaotfload has a way then to save data for new fonts, but I wonder what happens
if the already written database from YYY has references to font locations to which XXX
has not actual access (not tested).

Reported at http://tug.org/pipermail/tex-live/2016-May/038486.html

**Comment by phi-gamma** [comment] 2016-06-09 06:08
Hi!

···<date: 2016-05-16, Monday>···<from: Jean-François B.>···
> I have determined that luatex-cache is created in TEXMFSYSVAR if the user
> account has write access to it.

First off, the directory ``luatex-cache`` is part of the cache
management of the fontloader. If this ends up in the same
location where your ``$TEXMFSYSVAR`` resides, this would be a
side effect of some configuration setting. Luaotfload does *not*
intentionally choose that path.

On startup, the fontloader will determine the cache location by
picking the first nonempty value in this chain:

* kpse variable ``$TEXMFCACHE``;
* kpse variable ``$TEXMFVAR`` (no ``…SYS…``!);
* some common environment variables.
* ``$PWD``.

From whichever value was chosen it then proceeds with the first
writable path it contains.

It’s possible that one of these locations will be identical to
where your ``$TEXMFSYSVAR`` points.

>                                 This seems unexpected because if two
> users XXX and YYY both have write access then they could overwrite each other
> database (fonts may differ, as they may reside in personal folders).

If both have write access then that is by design. To prevent
that, they shouldn’t have write permissions. Full stop.

Best,
Philipp

**Comment by u-fischer** [comment] 2018-10-05 21:21
Closing as by design.

**Closed by u-fischer** 2018-10-05 21:21 UTC
